apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: k8s-utility-controller
  name: k8s-utility-controller
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-utility-controller
  template:
    metadata:
      labels:
        app: k8s-utility-controller
    spec:
      serviceAccountName: k8s-utility-controller
      containers:
      - image: skp123/k8s-utility-controller:v0.0.1
        args:
        - --log.level=debug
        - --server.host=0.0.0.0
        imagePullPolicy: Always
        name: k8s-util
        ports:
        - containerPort: 8080
          protocol: TCP
          name: http
        readinessProbe:
          httpGet:
            path: "/healthz"
            port: 8089
      restartPolicy: Always
