kind: Service
apiVersion: v1
metadata:
  name:  k8s-utility-controller
spec:
  selector:
    app: k8s-utility-controller
  type:  NodePort
  ports:
  - name:  http
    port:  8080
    targetPort:  8080